packages:
  - cf-eventhub
  - web-console
  - iac/pulumi
  - internal/*
catalog:
  wrangler: 4.22.0
  '@cloudflare/workers-types': 4.20250628.0
  '@cloudflare/vitest-pool-workers': 0.6.10
onlyBuiltDependencies:
  - esbuild
  - workerd
