packages:
  - cf-eventhub
  - eventhub
  - console
  - web-console
  - iac/pulumi
  - internal/*

catalog:
  "@cloudflare/vitest-pool-workers": 0.12.14
  "@cloudflare/workers-types": 4.20260219.0
  wrangler: 4.67.0

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@biomejs/biome"
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - workerd
