import { readFile, writeFile } from "node:fs/promises";

const css = await readFile(new URL("../src/app/styles.css", import.meta.url), "utf8");
const contents = `// This file is generated by \`pnpm --filter @cf-eventhub/web-console build:styles\`.
export const styles = ${JSON.stringify(css)};
`;

await writeFile(new URL("../src/app/styles.ts", import.meta.url), contents);
