name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm with runtime
        uses: pnpm/setup@v1

      - name: Type check - cf-eventhub
        working-directory: cf-eventhub
        run: pnpm tsc --noEmit
      - name: Test - cf-eventhub
        working-directory: cf-eventhub
        run: pnpm test

      - name: Type check - web-console
        working-directory: web-console
        run: pnpm tsc --noEmit

      - uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
          commit: Release npm packages
          title: Release npm packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
